/**
 * Copyright (C) 2025 Fabric Compatibility Layer Team
 *
 * Licensed under the Open Software License version 3.0
 */
package io.github.fabriccompatibilitylayers.fabricatedforge.mods.fabric.compat.modmenu;

import com.google.common.base.Strings;
import com.terraformersmc.modmenu.api.UpdateChecker;
import com.terraformersmc.modmenu.api.UpdateInfo;
import com.terraformersmc.modmenu.util.mod.Mod;
import com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler;
import cpw.mods.fml.common.ModContainer;
import io.github.fabriccompatibilitylayers.fabricatedfml.remapper.FileUtils;
import net.fabricmc.loader.api.FabricLoader;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.awt.image.BufferedImage;
import java.nio.file.FileSystem;
import java.nio.file.Path;
import java.util.*;

public class FMLMod implements Mod {
    public final ModContainer container;
    protected final Path rootPath;

    public FMLMod(ModContainer container) {
        this.container = container;
        Path path = null;

        if (container.getSource() != null && container.getSource().isFile()) {
            try {
                FileSystem fs = FileUtils.getJarFileSystem(container.getSource().toPath());
                path = fs.getRootDirectories().iterator().next();
            } catch (Exception e) {
                path = null;
            }
        }

        this.rootPath = path;
    }

    @Override
    public @NotNull String getId() {
        return "fml-" + container.getModId();
    }

    @Override
    public @NotNull String getName() {
        return container.getName();
    }

    @Override
    public @NotNull BufferedImage getIcon(FabricIconHandler fabricIconHandler, int i) {
        if (!container.getMetadata().autogenerated && !container.getMetadata().logoFile.isEmpty()) {
            BufferedImage image = ModMenuUtils.createIcon(fabricIconHandler, this);

            if (image != null) {
                return image;
            }
        }

        return fabricIconHandler.createIcon(FabricLoader.getInstance().getModContainer("modmenu").orElseThrow(() -> new RuntimeException("Cannot get ModContainer for Fabric mod with id modmenu")), "assets/modmenu/unknown_icon.png");
    }

    @Override
    public @NotNull String getDescription() {
        if (container.getMetadata().autogenerated) {
            return "No mod information found";
        }

        return container.getMetadata().description;
    }

    @Override
    public @NotNull String getVersion() {
        return container.getVersion();
    }

    @Override
    public @NotNull String getPrefixedVersion() {
        if (container.getMetadata().autogenerated) {
            return container.getVersion();
        }

        return container.getDisplayVersion();
    }

    @Override
    public @NotNull List<String> getAuthors() {
        if (container.getMetadata().autogenerated) {
            return Collections.emptyList();
        }

        return container.getMetadata().authorList;
    }

    @Override
    public @NotNull Map<String, Collection<String>> getContributors() {
        return Collections.emptyMap();
    }

    @Override
    public @NotNull SortedMap<String, Set<String>> getCredits() {
        SortedMap<String, Set<String>> credits = new TreeMap<>();
        credits.put("Credits", new LinkedHashSet<>());
        credits.get("Credits").addAll(Arrays.asList(container.getMetadata().credits.split(",")));
        List<String> authors = this.getAuthors();
        Map<String, Collection<String>> contributors = new HashMap<>();

        for(String author : authors) {
            contributors.put(author, Collections.singletonList("Author"));
        }

        for(Map.Entry<String, Collection<String>> contributor : contributors.entrySet()) {
            for(String role : contributor.getValue()) {
                credits.computeIfAbsent(role, (key) -> new LinkedHashSet<>());
                credits.get(role).add((String)contributor.getKey());
            }
        }

        return credits;
    }

    @Override
    public @NotNull Set<Badge> getBadges() {
        return Collections.emptySet();
    }

    @Override
    public @Nullable String getWebsite() {
        if (container.getMetadata().autogenerated) {
            return null;
        }

        return container.getMetadata().url;
    }

    @Override
    public @Nullable String getIssueTracker() {
        return null;
    }

    @Override
    public @Nullable String getSource() {
        return null;
    }

    @Override
    public @Nullable String getParent() {
        if (Strings.isNullOrEmpty(container.getMetadata().parent)) {
            return null;
        }

        return "fml-" + container.getMetadata().parent;
    }

    @Override
    public @NotNull Set<String> getLicense() {
        return Collections.emptySet();
    }

    @Override
    public @NotNull Map<String, String> getLinks() {
        return Collections.emptyMap();
    }

    @Override
    public boolean isReal() {
        return true;
    }

    @Override
    public boolean allowsUpdateChecks() {
        return false;
    }

    @Override
    public @Nullable UpdateChecker getUpdateChecker() {
        return null;
    }

    @Override
    public void setUpdateChecker(@Nullable UpdateChecker updateChecker) {

    }

    @Override
    public @Nullable UpdateInfo getUpdateInfo() {
        return null;
    }

    @Override
    public void setUpdateInfo(@Nullable UpdateInfo updateInfo) {

    }

    @Override
    public void setChildHasUpdate() {

    }

    @Override
    public boolean getChildHasUpdate() {
        return false;
    }

    @Override
    public boolean isHidden() {
        return false;
    }
}
