unimined.minecraft {
    mappings {
        devFallbackNamespace("searge")
        devNamespace("forgeMCP")
    }
}

configurations {
    production
}

artifacts {
    production remapJar
}

remapJar {
    remapAccessTransformer.set(false)
}

dependencies {
    implementation(project(":fabricated-fml"))
}