plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.1-SNAPSHOT' apply false
}

group project.maven_group

base {
    archivesName = project.archives_base_name
}

allprojects {
    apply(plugin: "xyz.wagyourtail.unimined")

    version project.version

    unimined.useGlobalCache = false

    unimined.neoForgedMaven()
    unimined.ornitheMaven()
    unimined.quiltMaven()
    unimined.modrinthMaven()
    unimined.jitpack()

    repositories {
        ivy {
            name = "fmllibs"
            url = "https://maven.wagyourtail.xyz/releases/fmllibs/"
            patternLayout {
                artifact("[artifact]-[revision].[ext]")
            }
            content {
                includeGroup("fmllibs")
            }
            metadataSources {
                it.artifact()
            }
        }
        repositories {
            maven { url = "https://maven.bawnorton.com/releases" }
        }

        mavenLocal()
    }

    configurations {
        ornitheImplementation
        compileOnly.extendsFrom ornitheImplementation
    }

    unimined.minecraft(sourceSets.main, true) {
        version project.minecraft_version

        mappings {
            calamus()

            forgeBuiltinMCP(project.forge_version)
        }

        legacyFabric {
            loader project.fabric_version

            if (project.hasProperty("access_widener") && !project.access_widener.isEmpty()) {
                accessWidener(project.file(project.access_widener))
//                afterEvaluate {
//                    mergeAws([
//                            atLegacy2aw(project.file(project.access_transformer), project.file("converted_at.accesswidener"), "official"),
//                            project.file("fabric-specific.accesswidener")
//                    ], project.mappings)
//                }
            }
        }

        runs {
            config("client") {
                jvmArgs += "-Dfabric-mod-remapper-api.dev"
            }
            config("server") {
                jvmArgs += "-Dfabric-mod-remapper-api.dev"
            }
        }

        minecraftRemapper.config {
            ignoreFieldDesc(true)
        }

        mods.remap(configurations.ornitheImplementation) {
            namespace("calamus")

            mixinRemap {
                enableBaseMixin()
                enableMixinExtra()
            }
        }
    }

    dependencies {
        implementation("com.google.guava:guava:12.0.1")
        implementation("fmllibs:argo:2.25")

        modImplementation("com.github.thecatcore.CursedMixinExtensions:fabric:1.0.0") {
            exclude(module: 'fabric-loader')
        }
        // Published version of MRAPI
        modImplementation("maven.modrinth:mod-remapping-api:${project.mod_remapping_api}")

//        // Local version of MRAPI
//        modImplementation("io.github.fabriccompatibilitylayers:Mod-Remapping-API:1.26.2")

        modImplementation(fabricApi.legacyFabricModule("legacy-fabric-logger-api-v1", "1.9.1+1.12.2")) {
            exclude(module: 'fabric-loader')
        }
        modImplementation("maven.modrinth:spasm:0.2")

        modImplementation("com.github.thecatcore:WFVAIO:1.2.1") {
            exclude(module: 'fabric-loader')
        }

        implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.0-rc.2"))

        modImplementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.2.0"))

        fabricApi.osl(project.minecraft_version, project.osl_version).forEach {
            ornitheImplementation(it)
        }

        ornitheImplementation("com.terraformersmc:modmenu:${project.modmenu_version}+mc${project.minecraft_version}")
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    processResources {
        inputs.property "version", project.version
        inputs.property "mc_version", project.minecraft_version
        inputs.property "mrapi_version", project.mod_remapping_api

        filesMatching("fabric.mod.json") {
            expand "version": project.version,
                    "mc_version": rootProject.minecraft_version,
                    "mrapi_version": project.mod_remapping_api
        }
    }
}

unimined.minecraft {
}

subprojects.forEach {
    remapJar.dependsOn("${it.path}:remapJar")
}

dependencies {
    include("fmllibs:argo:2.25")
    include("io.github.llamalad7:mixinextras-fabric:0.5.0-rc.2")
    include("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.2.0")

    afterEvaluate {
        subprojects.forEach {
            include(project(path: "${it.path}", configuration: 'production'))
        }
    }
}