plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.2-SNAPSHOT' apply false
}

group project.maven_group

base {
    archivesName = project.archives_base_name
}

def ornitheLibraries = [
        "com.google.code.gson:gson:2.10",
        "commons-codec:commons-codec:1.9",
        "commons-io:commons-io:2.4",
        "commons-logging:commons-logging:1.1.3",
        "it.unimi.dsi:fastutil:8.5.9",
        "net.ornithemc:logger-config:1.0.0",
        "org.apache.commons:commons-compress:1.8.1",
        "org.apache.commons:commons-lang3:3.1",
        "org.apache.httpcomponents:httpclient:4.3.3",
        "org.apache.httpcomponents:httpcore:4.3.2",
        "org.apache.logging.log4j:log4j-api:2.19.0",
        "org.apache.logging.log4j:log4j-core:2.19.0",
        "org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0",
        "org.slf4j:slf4j-api:2.0.1"
]

allprojects {
    apply(plugin: "xyz.wagyourtail.unimined")

    version project.version

    unimined.useGlobalCache = false

    unimined.neoForgedMaven()
    unimined.ornitheMaven()
    unimined.quiltMaven()
    unimined.modrinthMaven()
    unimined.jitpack()

    repositories {
        ivy {
            name = "fmllibs"
            url = "https://maven.wagyourtail.xyz/releases/fmllibs/"
            patternLayout {
                artifact("[artifact]-[revision].[ext]")
            }
            content {
                includeGroup("fmllibs")
            }
            metadataSources {
                it.artifact()
            }
        }
        maven { url = "https://maven.bawnorton.com/releases" }
        maven {
            url = "https://jvmdowngrader.wagyourtail.xyz/maven/"
        }

        mavenLocal()
    }

    configurations {
        ornitheImplementation
        modImplementation.extendsFrom ornitheImplementation
    }

    unimined.minecraft(sourceSets.main, true) {
        version project.minecraft_version

        mappings {
            calamus()

            forgeBuiltinMCP(project.forge_version)

            stubs(["official", "searge", "calamus", "legacyIntermediary", "forgeMCP"]) {
                k("", "net/minecraft/src/", "net/minecraft/unmapped/", "net/minecraft/", "net/minecraft/src/")
                c("BaseMod", "net/minecraft/src/BaseMod", "net/minecraft/unmapped/BaseMod", "net/minecraft/BaseMod", "net/minecraft/src/BaseMod")
                c("EntityRendererProxy", "net/minecraft/src/EntityRendererProxy", "net/minecraft/unmapped/EntityRendererProxy", "net/minecraft/EntityRendererProxy", "net/minecraft/src/EntityRendererProxy")
                c("FMLRenderAccessLibrary", "net/minecraft/src/FMLRenderAccessLibrary", "net/minecraft/unmapped/FMLRenderAccessLibrary", "net/minecraft/FMLRenderAccessLibrary", "net/minecraft/src/FMLRenderAccessLibrary")
                c("MLProp", "net/minecraft/src/MLProp", "net/minecraft/unmapped/MLProp", "net/minecraft/MLProp", "net/minecraft/src/MLProp")
                c("ModLoader", "net/minecraft/src/ModLoader", "net/minecraft/unmapped/ModLoader", "net/minecraft/ModLoader", "net/minecraft/src/ModLoader")
                c("ModTextureAnimation", "net/minecraft/src/ModTextureAnimation", "net/minecraft/unmapped/ModTextureAnimation", "net/minecraft/ModTextureAnimation", "net/minecraft/src/ModTextureAnimation")
                c("ModTextureStatic", "net/minecraft/src/ModTextureStatic", "net/minecraft/unmapped/ModTextureStatic", "net/minecraft/ModTextureStatic", "net/minecraft/src/ModTextureStatic")
                c("TradeEntry", "net/minecraft/src/TradeEntry", "net/minecraft/unmapped/TradeEntry", "net/minecraft/TradeEntry", "net/minecraft/src/TradeEntry")
            }
        }

        legacyFabric {
            loader project.fabric_version

            if (project.hasProperty("access_widener") && !project.access_widener.isEmpty()) {
                accessWidener(project.file(project.access_widener))
//                afterEvaluate {
//                    mergeAws([
//                            atLegacy2aw(project.file(project.access_transformer), project.file("converted_at.accesswidener"), "official"),
//                            project.file("fabric-specific.accesswidener")
//                    ], project.mappings)
//                }
            }
        }

        runs {
            config("client") {
                jvmArgs += "-Dfabric-mod-remapper-api.dev"
            }
            config("server") {
                jvmArgs += "-Dfabric-mod-remapper-api.dev"
            }
        }

        minecraftRemapper.config {
            ignoreFieldDesc(true)
        }

        mods {
            modImplementation {
                mixinRemap {
                    enableBaseMixin()
                    enableMixinExtra()
                }
            }

            remap(configurations.ornitheImplementation) {
                namespace("calamus")

                mixinRemap {
                    enableBaseMixin()
                    enableMixinExtra()
                }
            }
        }
    }

    dependencies {
        implementation("com.google.guava:guava:12.0.1")
        implementation("fmllibs:argo:2.25")

        modImplementation("com.github.thecatcore.CursedMixinExtensions:fabric:1.0.0") {
            exclude(module: 'fabric-loader')
        }
        // Published version of MRAPI
        modImplementation("maven.modrinth:mod-remapping-api:${project.mod_remapping_api}")

//        // Local version of MRAPI
//        modImplementation("io.github.fabriccompatibilitylayers:mod-remapping-api:1.27.0")

        modImplementation(fabricApi.legacyFabric("${project.legacyfabric_version}+${project.minecraft_version}")) {
            exclude(module: 'fabric-loader')
        }
        modImplementation("maven.modrinth:spasm:0.2")

        modImplementation("com.github.thecatcore:WFVAIO:1.2.1") {
            exclude(module: 'fabric-loader')
        }

        modImplementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.2.0"))
        implementation("jvmdg-8.com.moulberry:mixinconstraints:1.0.9")

        fabricApi.osl(project.minecraft_version, project.osl_version).forEach {
            ornitheImplementation(it)
        }

        ornitheImplementation("com.terraformersmc:modmenu:${project.modmenu_version}+mc${project.minecraft_version}")

        ornitheLibraries.forEach {
            runtimeOnly(it)
        }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    processResources {
        inputs.property "version", project.version
        inputs.property "mc_version", project.minecraft_version
        inputs.property "mrapi_version", project.mod_remapping_api

        filesMatching("fabric.mod.json") {
            expand "version": project.version,
                    "mc_version": rootProject.minecraft_version,
                    "mrapi_version": project.mod_remapping_api
        }
    }
}

unimined.minecraft {
}

subprojects.forEach {
    remapJar.dependsOn("${it.path}:remapJar")
}

dependencies {
    include("fmllibs:argo:2.25")
    include("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.2.0")
    include("jvmdg-8.com.moulberry:mixinconstraints:1.0.9")
    include("xyz.wagyourtail.jvmdowngrader:jvmdowngrader-java-api:1.3.6:downgraded-8") {
        transitive = false
    }

    afterEvaluate {
        subprojects.forEach {
            include(project(path: "${it.path}", configuration: 'production'))
        }
    }
}