plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.1-SNAPSHOT' apply false
}

group project.maven_group
version project.version

base {
    archivesName = project.archives_base_name
}

allprojects {
    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

subprojects {
    apply(plugin: "xyz.wagyourtail.unimined")

    unimined.useGlobalCache = false

    unimined.neoForgedMaven()
    unimined.ornitheMaven()
    unimined.quiltMaven()
    unimined.modrinthMaven()
    unimined.jitpack()

    repositories {
        flatDir {
            dirs (rootProject.rootDir.toString() + "/libs")
        }
    }

    configurations {
        ornitheImplementation
    }

    unimined.minecraft {
        version project.minecraft_version

        mappings {
            calamus()

            forgeBuiltinMCP(project.forge_version)

            if (project.mappings == "searge") {
                devNamespace("searge")
            } else {
                devFallbackNamespace("searge")
                devNamespace("forgeMCP")
            }
        }

        legacyFabric {
            loader project.fabric_version
        }

        minecraftRemapper.config {
            ignoreFieldDesc(true)
        }

        mods.remap(configurations.ornitheImplementation) {
            namespace("calamus")
        }
    }

    dependencies {
        implementation(group: "local", name: "argo", version: "2.25")
        implementation(group: "local", name: "guava", version: "12.0.1")

        implementation("com.github.thecatcore.CursedMixinExtensions:fabric:1.0.0") {
            exclude(module: 'fabric-loader')
        }
        modImplementation("maven.modrinth:mod-remapping-api:${project.mod_remapping_api}")

        if (project.file(".gradle/unimined/local/modTransform/core-0.6.0-mapped-${project.mappings}.jar").exists()) {
            fabricApi.osl(project.minecraft_version, project.osl_version).forEach {
                modImplementation(ornitheImplementation(it))
            }

            modImplementation(ornitheImplementation("com.terraformersmc:modmenu:${project.modmenu_version}+mc${project.minecraft_version}"))
        } else {
            fabricApi.osl(project.minecraft_version, project.osl_version).forEach {
                ornitheImplementation(it)
            }

            ornitheImplementation("com.terraformersmc:modmenu:${project.modmenu_version}+mc${project.minecraft_version}")
        }
    }
}