org.gradle.jvmargs=-Xmx2G

version = 3.1.0
maven_group = io.github.fabriccompatibilitylayers
archives_base_name = fabricated-legacy-forge

minecraft_version = 1.4
forge_version = 5.0.0.326
fabric_loader_version = 0.18.2

mod_remapping_api=1.28.3
legacyfabric_version=1.18.3
lf_minecraft_version = 1.4.7
osl_version=0.20.0-alpha.4
modmenu_version=0.4.0
modmenu_minecraft_version = 1.4.7

ccc_version=
nei_version=

target=ornithe