unimined.minecraft {
//    mappings {
//        devFallbackNamespace("searge")
//        devNamespace("forgeMCP")
//    }
}

configurations {
    production
}

artifacts {
    production remapJar
}

dependencies {
    implementation(project(":fabricated-fml"))
    implementation(project(":fabricated-forge"))

    if (rootProject.target == "legacy-fabric") {
        ornitheImplementation("net.legacyfabric.ornithed.legacy-fabric-api:legacy-fabric-api:${project.legacyfabric_version}+${project.minecraft_version}") {
            exclude(module: 'fabric-loader')
        }

        fabricApi.osl(2, project.minecraft_version, project.osl_version).forEach {
            ornitheImplementation(it)
        }

        ornitheImplementation("com.terraformersmc:modmenu:${project.modmenu_version}+mc${project.minecraft_version}")
    } else {
        modImplementation("net.legacyfabric.ornithed.legacy-fabric-api:legacy-fabric-api:${project.legacyfabric_version}+${project.minecraft_version}") {
            exclude(module: 'fabric-loader')
        }

        fabricApi.osl(2, project.minecraft_version, project.osl_version).forEach {
            modImplementation(it)
        }

        modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}+mc${project.minecraft_version}")
    }
}