unimined.minecraft {
//    mappings {
//        devFallbackNamespace("searge")
//        devNamespace("forgeMCP")
//    }
}

configurations {
    production
}

artifacts {
    production remapJar
}

dependencies {
    implementation(project(":fabricated-fml"))
    implementation(project(":fabricated-forge"))

    if (!project.ccc_version.isEmpty()) mcpImplementation("maven.modrinth:codechicken-core:${project.ccc_version}")
    if (!project.nei_version.isEmpty()) mcpAtImplementation("maven.modrinth:nei:${project.nei_version}")
}